<?php

namespace Controllers;

/**
 * Generated by PHPUnit_SkeletonGenerator 1.2.0 on 2012-10-21 at 17:48:07.
 */
class loginTest extends \PHPUnit_Framework_TestCase {

	/**
	 * @var login
	 */
	protected $object;

	/**
	 * Sets up the fixture, for example, opens a network connection.
	 * This method is called before a test is executed.
	 */
	protected function setUp() {
		require_once (SITEPATH . 'lib/controller.php');   // get the autoloader working; delete this!!!
		require_once (SITEPATH . 'lib/view.php');   // get the autoloader working; delete this!!!
		require_once (SITEPATH . 'controllers/login.php');   // get the autoloader working; delete this!!!
		$this->object = new login;
	}

	/**
	 * Tears down the fixture, for example, closes a network connection.
	 * This method is called after a test is executed.
	 */
	protected function tearDown() {
		
	}

	/**
	 * @covers Controllers\login::index
	 * @todo   Implement testIndex().
	 */
	public function testIndex() {
	}

	/**
	 * @covers Controllers\login::loginAction
	 * @todo   Implement testLoginAction().
	 */
	public function testLoginAction() {
		$_POST['username'] = 'marion';
		$_POST['password'] = 'marion';
	}

	/**
	 * @covers Controllers\login::logoutAction
	 * @todo   Implement testLogoutAction().
	 */
	public function testLogoutAction() {
	}

}
